add first 2 pages for memory management session
Dlang-UPB/D-Summer-School pull request #28
Opened 2022-07-08 15:57 UTC by sorin-gabriel

Added the first 2 pages for the Memory Management session.
Waiting for review and suggestions regarding the quizzes, demos and what should be discussed on the 3rd page. I'm thinking of discussing memory allocation schemes, but this is more general and not necessarily related to D.

2022-07-15 13:14 UTC, edi33416 requested changes
The **Practice** sections are missing.
More details are needed.
Manual memory management isn't discussed: using malloc/free, using them in @safe @nogc code, D idioms.

You can grab a lot of info from [The GC Series](https://dlang.org/blog/the-gc-series/).
Please go through it and add what is meaningful to the lab

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/scope-and-lifetime.md
> +Global variables begin their lifetime at the start of the program and end it at the end of the program. They are kept in specific sections of the program (commonly, in ELFs: .data, .bss, .rodata). Th
`.data`, `.bss`, `.rodata`.
Add a short summary of what each section holds

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/scope-and-lifetime.md
> +Global variables begin their lifetime at the start of the program and end it at the end of the program. They are kept in specific sections of the program (commonly, in ELFs: .data, .bss, .rodata). Th
This is true for both global and static variables

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/scope-and-lifetime.md
> +Because we want to extend the lifetime of entities beyond a single program frame, using the stack is not suitable. Also, if the size or number of entities is not known at compile time, we again canno
> .. size or number of entities is not known at compile time, we again cannot use the stack.
size or number of entities is not known at compile time, we again cannot use the stack, as we don't know at compile time how much memory we need to reserve for our runtime variables.

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/man-vs-auto-and-gc.md
> +Appending elements to a dynamic array in this manner will trigger GC allocations when the capacity of the array is insufficient. You can see this by compiling the above code with the option ```-vgc``
Add a refresher on the differences between `size` and `capacity`. This will make the explanation easier to understand

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/man-vs-auto-and-gc.md
> +Now we can see exactly when the allocations take place. The output of the above snippet may look like this:
Explain the code above. Focus on the key parts. Add comments with `(1)`, `(2)` at the key points so you can refer them in the explanation.

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/man-vs-auto-and-gc.md
> +If we know exactly how much memory we need, we can preallocate it, triggering a single allocation:
You need to introduce why preallocating is important.
Add a small sample that appends a lot of `int`s to an array and time it. Do the same, this time preallocating the array. Compare the times. Drive home the point that allocating in a hot loop is bad, regardless of a GC or manual memory management, and that preallocating will always improve your run time

2022-07-15 13:14 UTC, edi33416 commented on docs/mem-management/man-vs-auto-and-gc.md
> +To reclaim memory, the GC keeps track of which blocks of memory are still accessible and which are not. The GC starts from locations known as program roots (implicitly, those are: the stacks of every
Why and when would a user use `addRoot` and `addRange`? Add samples and more details.

2022-07-18 09:14 UTC, RazvanN7 commented on docs/mem-management/auto-mem.md
> +- loops, especially if they run many times, should be responsible only for arithmetic, as this is the quickest and most predictable type of computation; we should avoid as much as possible having con
```suggestion
- loops, especially if they run many times, should be responsible only for arithmetic operations, as this is the quickest and most predictable type of computation.
We should avoid as much as possible having conditionals inside loops (all modern CPUs implement branch prediction strategies, which can generate a lot of mispredictions inside loops), and even more so, memory allocations, in which your program requests memory from the operating system, which in turn allocates physical memory.
```

2022-07-18 09:19 UTC, sorin-gabriel commented on docs/mem-management/intro-to-mem.md
> +You should already be familiar with those.
You mean line 20 or lines 16-20?

2022-07-18 09:23 UTC, sorin-gabriel commented on docs/mem-management/intro-to-mem.md
> +nav_order: 7
I don't think so; this is the order with respect to the other sessions.

2022-07-18 12:31 UTC, edi33416 commented on docs/mem-management/intro-to-mem.md
> +nav_order: 7
This order is ok. This defines the order of this section in the sidebar. It's children will start from 1

2022-07-18 13:03 UTC, edi33416 requested changes

2022-07-18 13:53 UTC, RazvanN7 approved these changes

2022-07-18 13:53 UTC, merged